db:
        image: mysql/mysql-server:5.7
        ports:
        - "3306:3306"
        environment:
        - "MYSQL_ROOT_PASSWORD=passe"
        - "MYSQL_USER=amin"
        - "MYSQL_PASSWORD=amine"
        - "MYSQL_DATABASE=my_db"

superapachephp:
        build: ./
        ports:
        - "8010:80"
        links:
        - "db:db"
        working_dir: "/home/docker"
